image: openjdk:8-jdk-slim

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle; chmod +x gradlew

cache:
  paths:
     - .gradle/

test:
  image: registry.gitlab.com/bitfireat/docker-android-emulator:latest
  tags:
    - privileged
  script:
    - start-emulator.sh
    - adb install src/androidTest/resources/org.dmfs.tasks_6880.apk
    - ./gradlew check connectedCheck
  artifacts:
    paths:
      - build/outputs/lint-results-debug.html
      - build/reports/

pages:
  script:
    - ./gradlew dokka
    - mkdir public && mv build/dokka public
  artifacts:
    paths:
      - public
  only:
    - master
